	INSERT INTO author (author_name, author_id) VALUES
('A. Bartlett Giamatti'),
('A. Elizabeth Delany'),
('A. Merritt'),
('A. Roger Merrill'),
('A. Walton Litz'),
('A.B. Yehoshua'),
('A.D.P. Briggs'),
('A.E. Cunningham'),
('A.E. van Vogt'),
('A.G. Pasquella'),
('A.H. Armstrong'),
('A.J. Arberry'),
('A.J. Ayer'),
('A.J. Jacobs'),
('A.J. McAllister'),
('A.M. Dellamonica'),
('A.M. Homes'),
('A.N. Roquelaure'),
('A.N. Wilson'),
('A.R. Braunmuller'),
('A.R. Taylor'),
('A.S. Byatt'),
('A.T. Hatto'),
('A.V. Miller'),
('Aaron Anderson'),
('Aaron Asher'),
('Aaron Medwin'),
('Aaron Rosenberg'),
('Aaron Shepard'),
('Abbe Wool'),
('Abbie Hoffman'),
('Abdul Rahman Munif'),
('Abdul-Karim Mustapha'),
('Abigail Adams'),
('Abigail Thomas'),
('Abolqasem Ferdowsi'),
('Abraham Lincoln'),
('Abraham Moore'),
('Adam Sexton'),
('Adam Drozdek'),
('Adam Gauntlett'),
('Adam Ginsberg'),
('Adam Golaski'),
('Adam Gopnik'),
('Adam Hargreaves'),
('Adam Haslett'),
('Adam Hochschild'),
('Adam Lesh'),
('Adam Long'),
('Adam Mansbach'),
('Adam Mars-Jones'),
('Adam McCauley'),
('Adam Phillips'),
('Adam Rex'),
('Adam Roberts'),
('Adam Smith'),
('Adam Swift'),
('Adam Woog'),
('Adam-Troy Castro'),
('Adela Pinch'),
('Adèle Geras'),
('Adèle Lang'),
('Adi Granov'),
('Adolfo Bioy Casares'),
('Adolfo Pérez Perdomo'),
('Adrian Reynolds'),
('Adrian Alphona'),
('Adrian Esteban'),
('Adrián Ferrero'),
('Adrian Geoffrey Gilbert'),
('Adrian Guelke'),
('Adrian Lester'),
('Adrian McKinty'),
('Adrian Wootton'),
('Adrienne Theimer'),
('Aeon J. Skoble'),
('Aeschylus'),
('Aesop'),
('Agatha Christie'),
('Agnes D. Kingston'),
('Agnolo di Cosimo Bronzino'),
('Ai Morinaga'),
('Aidan Hartley'),
('Aimé Césaire'),
('Aimee Bender'),
('Aimee Friedman'),
('Aine Greaney'),
('Akhil Sharma'),
('Akihiro Yamada'),
('Akira Watanabe'),
('Akira Yoshida'),
('Al Dempster'),
('Al Franken'),
('Al Gore'),
('Al Ries'),
('Al Rio'),
('Al Switzler'),
('Alafair Burke'),
('Alain de Botton'),
('Alain Defossé'),
('Alain Korkos'),
('Alak Zenkar'),
('Alan Lee'),
('Alan Aldridge'),
('Alan Brennert'),
('Alan Cohen'),
('Alan Dean Foster'),
('Alan Durband'),
('Alan Ereira'),
('Alan Greenspan'),
('Alan H. Sommerstein'),
('Alan Hausman'),
('Alan Hollinghurst'),
('Alan Jay Lerner'),
('Alan Jolis'),
('Alan Judd'),
('Alan Langford'),
('Alan Lightman'),
('Alan MacGillivray'),
('Alan Moore'),
('Alan Myers'),
('Alan Paton'),
('Alan R. Clarke'),
('Alan Rosenus'),
('Alan Shapiro'),
('Alan Witschonke'),
('Alastair Hamilton'),
('Alastair Hannay'),
('Alastair Lamb'),
('Alastair McEwen'),
('Alastair Reid'),
('Alastair Westgarth'),
('Albert Camus'),
('Albert Demeo'),
('Albert Einstein'),
('Albert Ellis'),
('Albert G. Spalding'),
('Albert Hackett'),
('Albert Hofstadter'),
('Albert Jack'),
('Albert Lee Strickland'),
('Albert Marrin'),
('Albert Speer'),
('Albert Wittstock'),
('Alberto Coscarelli'),
('Alcoholics Anonymous'),
('Alden T. Vaughan'),
('Aldon D. Morris'),
('Aldous Huxley'),
('Alec Effinger'),
('Alec MacLellan'),
('Alec Stevens'),
('Aleksandar Hemon'),
('Aleksandr Ivanovich Kuprin'),
('Aleksandr Solzhenitsyn'),
('Aleksey Ivanov'),
('Alev Lytle Croutier'),
('Alex Austin'),
('Alex C. Jones'),
('Alex Constantine'),
('Alex Cox'),
('Alex Garland'),
('Alex Gaskarth'),
('Alex Kava'),
('Alex Kershaw'),
('Alex Kotlowitz'),
('Alex Prud'Homme'),
('Alex Robinson'),
('Alex Ross'),
('Alex Went'),
('Alexander Walker'),
('Alexander C. Irvine'),
('Alexander Heidel'),
('Alexander Hunter'),
('Alexander McCall Smith'),
('Alexander Nehamas'),
('Alexander O. Smith'),
('Alexander Payne'),
('Alexander Pope'),
('Alexander Pushkin'),
('Alexander Scourby'),
('Alexander Theroux'),
('Alexandra Boiger'),
('Alexandra Ivy'),
('Alexandra Moss'),
('Alexandra Robbins'),
('Alexandra Siy'),
('Alexandra Wallner'),
('Alexandre Dumas'),
('Alexandre Dumas fils'),
('Alexis de Tocqueville'),
('Alexis Kirsch'),
('Alfred Appel'),
('Alfred Bester'),
('Alfred Birnbaum'),
('Alfred D. Chandler Jr.'),
('Alfred Hitchcock'),
('Alfred Huang'),
('Alfred J. Church'),
('Alfred Siewers'),
('Alfred Uhry'),
('Alfredo Crespo'),
('Algernon Blackwood'),
('Ali Douglass'),
('Ali Vali'),
('Alice Miller'),
('Alice Dalgliesh'),
('Alice Hoffman'),
('Alice Hudson'),
('Alice Kaplan'),
('Alice Mayhew'),
('Alice Medrich'),
('Alice Munro'),
('Alice Randall'),
('Alice Sebold'),
('Alice Walker'),
('Alice Wong'),
('Alicia Suskin Ostriker'),
('Alisa Freedman'),
('Alisa Klayman-Grodsky'),
('Alisa Valdes'),
('Alison Anderson'),
('Alison Baverstock'),
('Alison Bechdel'),
('Alison Boardman'),
('Alison Goodman'),
('Alison Kent'),
('Alison Leslie Gold'),
('Alison Lurie'),
('Alison Pace'),
('Alison Weir'),
('Alistair Horne'),
('Alistair MacLeod'),
('Alistair McCallum'),
('Alistair Moffat'),
('Alistair Welchman'),
('Alister E. McGrath'),
('Aljean Harmetz'),
('Allan Bloom'),
('Allan C. Weisbecker'),
('Allan Cameron'),
('Allan Curless'),
('Allan Drummond'),
('Allan Janik'),
('Allan Kozinn'),
('Allan Rosenberg'),
('Allan Ulrich'),
('Allan Zola Kronzek'),
('Allegra Goodman'),
('Allen Carr'),
('Allen Ginsberg'),
('Allen J. Frantzen'),
('Allen Mackey'),
('Allen Mandelbaum'),
('Allen Noren'),
('Allen Rogers Benner'),
('Allen W. Wood'),
('Allison Markin Powell'),
('Allison Pearson'),
('Alma Flor Ada'),
('Alma MacDougall Reising'),
('Alonzo C. Addison'),
('Alton Raible'),
('Alvin L. Reid'),
('Alyssa Harad'),
('Amanda Ann Klein'),
('Amanda Clark'),
('Amanda Eyre Ward'),
('Amanda Hemingway'),
('Amanda Hopkinson'),
('Amanda Root'),
('Amartya Sen'),
('Ambrose Bierce'),
('Amelia Atwater-Rhodes'),
('America's Test Kitchen'),
('American Academy of Pediatrics'),
('Amiira Ruotola (-Behrendt)'),
('Amir D. Aczel'),
('Amiri Baraka'),
('Amitav Ghosh'),
('Amos Oz'),
('Amy Berner'),
('Amy Carter'),
('Amy Cotler'),
('Amy Goldman Koss'),
('Amy Gutmann'),
('Amy H. Sturgis'),
('Amy Hempel'),
('Amy Hill Hearth'),
('Amy Krouse Rosenthal'),
('Amy L. Marsland'),
('Amy Mandelker'),
('Amy Sedaris'),
('Amy Sickels'),
('Amy Sohn'),
('Amy Tan'),
('Amy Taubin'),
('Amy Welborn'),
('Ana Alcaina'),
('Ana Alcaina Pérez'),
('Ana Falcão Bastos'),
('Ana Juan'),
('Ana María de la Fuente'),
('Anaïs Nin'),
('Anaximander'),
('Anaximenes'),
('Anca Munteanu'),
('Ande Parks'),
('Anders Nilsen'),
('Anderson Cooper'),
('Andre Dubus'),
('Andre Dubus III'),
('Andre Duza'),
('André Maurois'),
('Andre Norton'),
('Andrea Camilleri'),
('Andrea Juno'),
('Andrea Levy'),
('Andrea Lingenfelter'),
('Andrea Wilson Nightingale'),
('Andreas Schwarz'),
('Andreas Gursky'),
('Andreas J. Köstenberger'),
('Andrei Codrescu'),
('Andrés Duany'),
('Andrew Hunt'),
('Andrew Hunt'),
('Andrew Brown'),
('Andrew Carnegie'),
('Andrew Cartmel'),
('Andrew Collins'),
('Andrew Darling'),
('Andrew Delbanco'),
('Andrew Dennis'),
('Andrew Edwin Jenkins'),
('Andrew Elfenbein'),
('Andrew Ford'),
('Andrew Glass'),
('Andrew Gross'),
('Andrew Gurr'),
('Andrew Heintzman'),
('Andrew Helfer'),
('Andrew Hurley'),
('Andrew Hussey'),
('Andrew J. Offutt'),
('Andrew James McLean'),
('Andrew Klavan'),
('Andrew Lang'),
('Andrew Leak'),
('Andrew M. Greeley'),
('Andrew McNeillie'),
('Andrew Moore'),
('Andrew O'Hagan'),
('Andrew P. Trout'),
('Andrew Pepoy'),
('Andrew R. MacAndrew'),
('Andrew Robert Burn'),
('Andrew S. Becker'),
('Andrew Scull'),
('Andrew Solomon'),
('Andrew Weil'),
('Andrew X. Pham'),
('Andy Crouch'),
('Andy Frankham-Allen'),
('Andy Gordon'),
('Andy Griffiths'),
('Andy Grundberg'),
('Andy Hertzfeld'),
('Andy Hunt'),
('Andy Kubert'),
('Andy Mastrocinque'),
('Andy McNab'),
('Andy Russell'),
('Andy Warhol'),
('Anette M. Pedersen'),
('Angel M.Y. Lin'),
('Angela Barrett'),
('Angela Carter'),
('Angela J. Linn'),
('Angela Knight'),
('Angela Scholar'),
('Angela Zeman'),
('Angelo Rinaldi'),
('Angus Easson'),
('Angus Gellatly'),
('Angus Wells'),
('Anita Desai'),
('Anita Diamant'),
('Anita Hoffman'),
('Anita Shreve'),
('Anita Thompson'),
('Anjali Singh'),
('Anjelica Huston'),
('Ann Douglas'),
('Ann O'Leary'),
('Ann Abramson'),
('Ann Bausum'),
('Ann Beattie'),
('Ann Brashares'),
('Ann Charters'),
('Ann Druyan'),
('Ann Dunnigan'),
('Ann Finding'),
('Ann Granger'),
('Ann Hewetson'),
('Ann Hodgman'),
('Ann M. Martin'),
('Ann Major'),
('Ann Margaret Lewis'),
('Ann Maxwell'),
('Ann McGovern'),
('Ann Packer'),
('Ann Page'),
('Ann Patchett'),
('Ann Rinaldi'),
('Ann Romines'),
('Ann Rule'),
('Ann Schweninger'),
('Ann Tashi Slater'),
('Ann Thompson'),
('Ann Thwaite'),
('Ann-Marie MacDonald'),
('Anna Austen Lefroy'),
('Anna Brailovsky'),
('Anna Deavere Smith'),
('Anna Fields'),
('Anna Hamilton Phelan'),
('Anna J.'),
('Anna J. Evans'),
('Anna Massey'),
('Anna Maxted'),
('Anna Moschovakis'),
('Anna Okabe'),
('Anna Paterson'),
('Anna Quindlen'),
('Anna Sewell'),
('Anna Tambour'),
('Anna Wintour'),
('Annalee Allen'),
('Annalyn Swan'),
('Anne Born'),
('Anne Borchardt'),
('Anne Brontë'),
('Anne Carson'),
('Anne Chisholm'),
('Anne Dehne'),
('Anne Easter Smith'),
('Anne Elizabeth Moore'),
('Anne Fadiman'),
('Anne Frank'),
('Anne Hoppus'),
('Anne K. Mellor'),
('Anne Lamott'),
('Anne Macdonald'),
('Anne Mazer'),
('Anne McCaffrey'),
('Anne McLean'),
('Anne Michaels'),
('Anne Millard'),
('Anne Moody'),
('Anne Morrow Lindbergh'),
('Anne Olivier Bell'),
('Anne Perry'),
('Anne Rampling'),
('Anne Rice'),
('Anne Stuart'),
('Anne Tyler'),
('Anne Yvonne Gilbert'),
('Anne-Marie Duff'),
('Anne-Marie Martin'),
('Annette Lavers'),
('Annette Meyers'),
('Annette Smith'),
('Annie Dillard'),
('Annie Proulx'),
('Annie Sparrow'),
('Anonymous'),
('Anri Itō'),
('Ansel Adams'),
('Anselm of Canterbury'),
('Anthea Bell'),
('Anthony Lewis'),
('Anthony Bonner'),
('Anthony Boucher'),
('Anthony Bourdain'),
('Anthony Bower'),
('Anthony Briggs'),
('Anthony Burgess'),
('Anthony Calderbank'),
('Anthony Cronin'),
('Anthony Curtis'),
('Anthony D. Pellegrini'),
('Anthony DeCurtis'),
('Anthony E. Wolf'),
('Anthony F.C. Wallace'),
('Anthony Gerard'),
('Anthony Grafton'),
('Anthony H. Chambers'),
('Anthony Heald'),
('Anthony Hern'),
('Anthony J. Cascardi'),
('Anthony Kenny'),
('Anthony Kerringan'),
('Anthony Kiedis'),
('Anthony Loyd'),
('Anthony M. Esolen'),
('Anthony Mcreavy'),
('Anthony Minghella'),
('Anthony Oldcorn'),
('Anthony Powell'),
('Anthony Quinton'),
('Anthony Richard Birley'),
('Anthony Rizcallah Ferris'),
('Anthony Robbins'),
('Anthony S. Fauci'),
('Anthony Shadid'),
('Anthony Thorlby'),
('Anthony Thwaite'),
('Anthony Tully'),
('Antoine de Saint-Exupéry'),
('Anton C. Pegis'),
('Anton Chekhov'),
('Anton Lesser'),
('Anton Myrer'),
('Antonia Fraser'),
('Antonia Juhasz'),
('Antonin Artaud'),
('Antonina W. Bouis'),
('Antonio Gramsci'),
('Antonio Negri'),
('Antonio Polito'),
('Antonio Samons'),
('Antony Beevor'),
('Antony Johnston'),
('Antony Shugaar'),
('Anya Seton'),
('Apollodorus'),
('Apostolos N. Athanassakis'),
('April Jones Prince'),
('Architecture For Humanity'),
('Ariel Levy'),
('Arielle Ford'),
('Arien Mack'),
('Aristophanes'),
('Aristotle'),
('Arkangel Cast'),
('Arlene Eisenberg'),
('Arliss Howard'),
('Armand Marie Leroi'),
('Armistead Maupin'),
('Arnold Gingrich'),
('Arnold Goldman'),
('Arnold Kotler'),
('Arnold Rampersad'),
('Arnold Vedlitz'),
('Arnon Grunberg'),
('Aron Eisenberg'),
('Art Cooper'),
('Art Spiegelman'),
('Art Spielman'),
('Art Thibert'),
('Artem Drabkin'),
('Artemis Cooper'),
('Arthur Miller'),
('Arthur Agatston'),
('Arthur Bennett'),
('Arthur C. Clarke'),
('Arthur Conan Doyle'),
('Arthur Cooper'),
('Arthur Doye'),
('Arthur Edward Waite'),
('Arthur G. Chater'),
('Arthur Golden'),
('Arthur Goldhammer'),
('Arthur H. Samuelson'),
('Arthur Herzog III'),
('Arthur J. Roth'),
('Arthur Knodel'),
('Arthur Koestler'),
('Arthur M. Schlesinger Jr.'),
('Arthur Machen'),
('Arthur Morey'),
('Arthur Naiman'),
('Arthur Nersesian'),
('Arthur P. Yin'),
('Arthur Plotnik'),
('Arthur Pober'),
('Arthur Rackham'),
('Arthur Raleigh Humphreys'),
('Arthur S. Wensinger'),
('Arthur Schopenhauer'),
('Arthur Yorinks'),
('Artists and Writers Guild'),
('Arto Häilä'),
('Arturo Pérez-Reverte'),
('Arundhati Roy'),
('Ashley Gardner'),
('Ashley Shannon'),
('Ashley Wood'),
('Åsne Seierstad'),
('Astre Mithrandir'),
('Astrid Lindgren'),
('Atul Gawande'),
('Aubrey de Sélincourt'),
('Aubrey Williams'),
('Audre Lorde'),
('Audrey Niffenegger'),
('Audrey Penn'),
('August Derleth'),
('August Wilson'),
('Augusten Burroughs'),
('Augustine of Hippo'),
('Aurelio Voltaire'),
('Aurora Echevarría'),
('Austin Tichenor'),
('Avatar Polymorph'),
('Avi'),
('Avigdor Kahalani'),
('Avrahm Yarmolinsky'),
('Ayako Watanabe'),
('Aylmer Maude'),
('Ayn Rand'),
('Azar Nafisi'),
('Azzedine Haddour'),
('B. Deutsch'),
('B. Litt'),
('B.B. Rogers'),
('B.C.J.G. Knight'),
('B.J. McCall'),
('B.K. Beckwith'),
('Babette Rothschild'),
('Babette Smith'),
('Bagram Ibatoulline'),
('Baillie Tolkien'),
('Bambi Eloriaga'),
('Barack Obama'),
('Barb Jernigan'),
('Barbara Newman'),
('Barbara A. Mowat'),
('Barbara A. Turner'),
('Barbara Ann Brennan'),
('Barbara Berst Adams'),
('Barbara Bottner'),
('Barbara Bray'),
('Barbara Bretton'),
('Barbara Caruso'),
('Barbara Cleverly'),
('Barbara Cohen'),
('Barbara Coloroso'),
('Barbara Conklin'),
('Barbara Cooney'),
('Barbara Davilman'),
('Barbara Delaplace'),
('Barbara E. Martin'),
('Barbara Ehrenreich'),
('Barbara Fairchild'),
('Barbara Hambly'),
('Barbara Haworth-Attard'),
('Barbara Kerley'),
('Barbara Kingsolver'),
('Barbara Leonie Picard'),
('Barbara M. Walker'),
('Barbara Nadel'),
('Barbara Park'),
('Barbara Reynolds'),
('Barbara Richard'),
('Barbara Siegel'),
('Barbara Smuts'),
('Barbara T. Cooper'),
('Barbara Taylor Bradford'),
('Barbara W. Tuchman'),
('Barbara Weiden Boyd'),
('Barbara Wright'),
('Bard E. O'Neill'),
('Bard Thompson'),
('Barney Tobey'),
('Barrett Whitener'),
('Barrie D. Coate'),
('Barrie Trinkle'),
('Barrington Moore Jr.'),
('Barron's'),
('Barry Lopez'),
('Barry Smith'),
('Barry Chubin'),
('Barry Day'),
('Barry Eisler'),
('Barry Glassner'),
('Barry Hughart'),
('Barry M. Andrews'),
('Barry Menikoff'),
('Barry Miles'),
('Barry Moser'),
('Barry N. Malzberg'),
('Barry Pateman'),
('Barry R. Cournoyer'),
('Barry Schwartz'),
('Barry Z. Posner'),
('Bart D. Ehrman'),
('Bart G. Farkas'),
('Bart King'),
('Barthe DeClements'),
('Bartholomew Gill'),
('Barton Zwiebach'),
('Baruch Spinoza'),
('Basil Mahon'),
('Basil Pao'),
('Basilio Losada'),
('Bathroom Readers' Institute'),
('Be-Papas'),
('Be-Pas'),
('Beatrix Potter'),
('Beau Bridges'),
('Bebe Moore Campbell'),
('Becky Ann Baker'),
('bell hooks'),
('Belva Plain'),
('Ben Avery'),
('Ben Bova'),
('Ben Carson'),
('Ben Counter'),
('Ben Elton'),
('Ben Katchor'),
('Ben M. Baglio'),
('Ben Marcus'),
('Ben Mezrich'),
('Ben Mikaelsen'),
('Ben Ohlander'),
('Ben Oliver'),
('Ben R. Kaplan'),
('Ben Schoen'),
('Ben Schott'),
('Ben Shahn'),
('Ben Templesmith'),
('Ben Wasson'),
('Benjamin Beard'),
('Benjamin Chaud'),
('Benjamin DeMott'),
('Benjamin F. Fisher'),
('Benjamin James Sadock'),
('Benjamin Jowett'),
('Benjamin Martinez'),
('Bennett Cerf'),
('Bentley Little'),
('Berlitz Publishing Company'),
('Bernard Bador'),
('Bernard Cohen'),
('Bernard Cornwell'),
('Bernard DeVoto'),
('Bernard Frechtman'),
('Bernard Knox'),
('Bernard Lewis'),
('Bernard Malamud'),
('Bernard Taper'),
('Bernard Williams'),
('Bernd Matzkowski'),
('Bernice Kert'),
('Bernie Wrightson'),
('Bert G. Hornback'),
('Berta Platas'),
('Bertrand Russell'),
('Beryl Bainbridge'),
('Beryl Markham'),
('Bessie Head'),
('Beth A. Jones'),
('Beth Chaplin'),
('Beth Cuthand'),
('Beth Dunfey'),
('Beth Hensperger'),
('Beth Kendrick'),
('Beth Moore'),
('Bethany Roberts'),
('Betina Ogden'),
('Betsy Lewin'),
('Bette Greene'),
('Better Homes and Gardens'),
('Bettina Blanch Tyroller'),
('Betty Smith'),
('Betty David'),
('Betty Friedan'),
('Betty Jay'),
('Betty MacDonald'),
('Betty Mahmoody'),
('Betty McCollum'),
('Betty Neels'),
('Betty Radice'),
('Bev Vincent'),
('Beverly Cleary'),
('Beverly Daniel Tatum'),
('Bianca Southwood'),
('Bill Phillips'),
('Bill Bryson'),
('Bill Bettencourt'),
('Bill Brittain'),
('Bill Brown'),
('Bill Bryson'),
('Bill Buford'),
('Bill Clinton'),
('Bill Cosby'),
('Bill Dodge'),
('Bill Farrel'),
('Bill Fawcett'),
('Bill Gardner'),
('Bill Hurter'),
('Bill Hybels'),
('Bill Irwin'),
('Bill Johnston'),
('Bill Maher'),
('Bill Miller'),
('Bill Moyers'),
('Bill Nichols'),
('Bill Phillips'),
('Bill Pittman'),
('Bill Plaschke'),
('Bill Potter'),
('Bill Pronzini'),
('Bill Richardson'),
('Bill Robertie'),
('Bill Sienkiewicz'),
('Bill Veeck'),
('Bill Watterson'),
('Bill Willingham'),
('Bill Wittliff'),
('Billie Letts'),
('Billy Collins'),
('Billy Crystal'),
('Billy Goldberg'),
('Billy Merrell'),
('Billy Mills'),
('Billy Wilder'),
('Binjamin W. Segel'),
('Birgit Brandau'),
('Black Elk'),
('Blaine M. Yorgason'),
('Blair Brown'),
('Blaise Pascal'),
('Blake Cahoon'),
('Blake Morrison'),
('Blake Nelson'),
('Blake Nevius'),
('Blanca Ríos'),
('Bob Smith'),
('Bob Blaisdell'),
('Bob Carrau'),
('Bob Colacello'),
('Bob Cullen'),
('Bob Dylan'),
('Bob Haney'),
('Bob Hines'),
('Bob Lappan'),
('Bob Madgic'),
('Bob Marley'),
('Bob McCabe'),
('Bob McLeod'),
('Bob Phillips'),
('Bob Shaw'),
('Bob Spitz'),
('Bob Tarte'),
('Bob Walters'),
('Bob Woodward'),
('Bobbi Smith'),
('Bobby Baldwin'),
('Bobby Flay'),
('Bobby Henderson'),
('Bodie Thoene'),
('Boethius'),
('Boniface Ramsey'),
('Bonnie Burton'),
('Bonnie Kime Scott'),
('Bonnie Lisle'),
('Bonnie Mackain'),
('Bonnie Timmons'),
('Borden Deal'),
('Boris Grabnar'),
('Boris Pasternak'),
('Boris Vian'),
('Brad Inwood'),
('Brad Leithauser'),
('Brad Meltzer'),
('Brad Thor'),
('Brad Walker'),
('Brady Games'),
('Bram Stoker'),
('Brandon Badeaux'),
('Brandon Mull'),
('Brantley Johnson'),
('Brenda Cooper'),
('Brenda G. Bare'),
('Brenda Jackson'),
('Brenda Joyce'),
('Brenda K. Marshall'),
('Brenda Novak'),
('Brenda Walpole'),
('Brendan Connell'),
('Brendan DuBois'),
('Brendan Frayne'),
('Brendan Gill'),
('Brent Hoff'),
('Brenton G. Yorgason'),
('Breon Mitchell'),
('Bret Easton Ellis'),
('Bret Norris'),
('Brett Booth'),
('Brett Hartinge'),
('Brian Doyle'),
('Brian Nelson'),
('Brian Phillips'),
('Brian Wood'),
('Brian Ajhar'),
('Brian Antoni'),
('Brian Azzarello'),
('Brian Bolland'),
('Brian Boyd'),
('Brian Braithwaite'),
('Brian Campbell'),
('Brian Ching'),
('Brian Copeland'),
('Brian D. McLaren'),
('Brian Doherty'),
('Brian Floca'),
('Brian Greene'),
('Brian Hall'),
('Brian Herbert'),
('Brian Hooker'),
('Brian J. Robb'),
('Brian Jacques'),
('Brian James'),
('Brian James Freeman'),
('Brian Johnston'),
('Brian K. Vaughan'),
('Brian L. Weiss'),
('Brian M. Sammons'),
('Brian McGuinness'),
('Brian McNaughton'),
('Brian Michael Bendis'),
('Brian Nishil'),
('Brian P. Flannery'),
('Brian Rotman'),
('Brian Selznick'),
('Brian Sibley'),
('Brian Stableford'),
('Brian Stone'),
('Brian Tracy'),
('Brian Troxell'),
('Brian Unger'),
('Brian W. Aldiss'),
('Brian Yoon'),
('Brice Matthieussent'),
('Bridget Foley'),
('Brigid Avison'),
('Brigitte Lefevre'),
('Brion Gysin'),
('Brittiany A. Koren'),
('Brock Thoene'),
('Brooke Allen'),
('Broughton Coburn'),
('Brown'),
('Bruce Alvin King'),
('Bruce Arnold'),
('Bruce Bethke'),
('Bruce Campbell'),
('Bruce Catton'),
('Bruce Coville'),
('Bruce Cumings'),
('Bruce Degen'),
('Bruce E. Bursten'),
('Bruce Edward Walker'),
('Bruce Feiler'),
('Bruce H. Wilkinson'),
('Bruce Harbert'),
('Bruce Holland Rogers'),
('Bruce Kuklick'),
('Bruce L. Edwards'),
('Bruce Patton'),
('Bruce Rogers'),
('Bruce Spizer'),
('Bruce Sterling'),
('Bryan Collier'),
('Bryan Hitch'),
('Bryan J.L. Glass'),
('Bryan Lee O'Malley'),
('Bryan Magee'),
('Bryan Sykes'),
('Bryan Talbot'),
('Bryan W. Van Norden'),
('Bryce Courtenay'),
('Buchi Emecheta'),
('Buck Schirner'),
('Burt Reynolds'),
('Burton G. Malkiel'),
('Burton Pike'),
('Burton Raffel'),
('Butch Patrick'),
('Buzz Aldrin'),
('Buzz Bissinger'),
('C. Hassell Bullock'),
('C. Michael Dudash'),
('C. Patrick Doncaster'),
('C. Thomas Wass'),
('C. Vann Woodward'),
('C.B. Cebulski'),
